name: Build OOHD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            cmake_generator: "Visual Studio 17 2022"
          - os: macos-latest
            cmake_generator: "Xcode"

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -G "${{matrix.cmake_generator}}" -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Release

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OOHD-${{ matrix.os }}
        path: ${{github.workspace}}/build/Release/oohd*
