jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: mkdir -p build && cd build && cmake .. && make
    - name: Deploy
      run: echo Deploying...
name: CI
on:
- push
- pull_request
