jobs:
  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: mkdir -p build && cd build && cmake .. && make
    - name: Locate Executable
      run: "\n                executable=$(find build -type f -executable -print -quit)\n                echo \"EXECUTABLE_PATH=$executable\" >> $GITHUB_ENV\n                if [ -z \"$executable\" ]; then\n                    echo \"No executable found\"\n                    exit 1\n                fi\n            "
    - name: Debug - List Build Output
      run: "\n                echo \"Listing build directory:\"\n                ls -R build\n                echo \"Executable path: $EXECUTABLE_PATH\"\n            "
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-latest-artifact
        path: ${{ env.EXECUTABLE_PATH }}
        retention-days: 1
    - env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/octet-stream
        asset_name: oohd-macos-latest
        asset_path: ${{ env.EXECUTABLE_PATH }}
        upload_url: https://uploads.github.com/repos/RPDevJesco/OOHD/releases/164922683/assets
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: mkdir -p build && cd build && cmake .. && make
    - name: Locate Executable
      run: "\n                executable=$(find build -type f -executable -print -quit)\n                echo \"EXECUTABLE_PATH=$executable\" >> $GITHUB_ENV\n                if [ -z \"$executable\" ]; then\n                    echo \"No executable found\"\n                    exit 1\n                fi\n            "
    - name: Debug - List Build Output
      run: "\n                echo \"Listing build directory:\"\n                ls -R build\n                echo \"Executable path: $EXECUTABLE_PATH\"\n            "
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-latest-artifact
        path: ${{ env.EXECUTABLE_PATH }}
        retention-days: 1
    - env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/octet-stream
        asset_name: oohd-ubuntu-latest
        asset_path: ${{ env.EXECUTABLE_PATH }}
        upload_url: https://uploads.github.com/repos/RPDevJesco/OOHD/releases/164922683/assets
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: mkdir build && cd build && cmake .. && cmake --build . --config Release
    - name: Locate Executable
      run: "\n                $executable = Get-ChildItem -Path build -Recurse -File | Where-Object { $_.Name -like \"*.exe\" } | Select-Object -First 1 -ExpandProperty FullName\n                echo \"EXECUTABLE_PATH=$executable\" >> $env:GITHUB_ENV\n                if (-not $executable) {\n                    echo \"No executable found\"\n                    exit 1\n                }\n            "
    - name: Debug - List Build Output
      run: "\n                echo \"Listing build directory:\"\n                Get-ChildItem -Path build -Recurse\n                echo \"Executable path: $env:EXECUTABLE_PATH\"\n            "
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-latest-artifact
        path: ${{ env.EXECUTABLE_PATH }}
        retention-days: 1
    - env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/octet-stream
        asset_name: oohd-windows-latest.exe
        asset_path: ${{ env.EXECUTABLE_PATH }}
        upload_url: https://uploads.github.com/repos/RPDevJesco/OOHD/releases/164922683/assets
name: CI
on:
- push
- pull_request
