jobs:
  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build C++
      run: mkdir -p build && cd build && cmake .. && make
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-latest-artifact
        path: build/OOHD
        retention-days: 1
    - env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/octet-stream
        asset_name: OOHD-macos-latest
        asset_path: build/OOHD
        upload_url: https://uploads.github.com/repos/RPDevJesco/OOHD/releases/164910154/assets{?name,label}
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build C++
      run: mkdir -p build && cd build && cmake .. && make
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-latest-artifact
        path: build/OOHD
        retention-days: 1
    - env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/octet-stream
        asset_name: OOHD-ubuntu-latest
        asset_path: build/OOHD
        upload_url: https://uploads.github.com/repos/RPDevJesco/OOHD/releases/164910154/assets{?name,label}
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build C++
      run: mkdir build && cd build && cmake .. && cmake --build .
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-latest-artifact
        path: build/OOHD.exe
        retention-days: 1
    - env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/octet-stream
        asset_name: OOHD-windows-latest.exe
        asset_path: build/OOHD.exe
        upload_url: https://uploads.github.com/repos/RPDevJesco/OOHD/releases/164910154/assets{?name,label}
  verify_artifacts:
    name: Verify Artifacts
    needs:
    - build_ubuntu
    - build_macos
    - build_windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download ubuntu-latest Artifact
      uses: actions/download-artifact@v4
      with:
        name: ubuntu-latest-artifact
        path: ./ubuntu-latest-artifact
    - name: Download macos-latest Artifact
      uses: actions/download-artifact@v4
      with:
        name: macos-latest-artifact
        path: ./macos-latest-artifact
    - name: Download windows-latest Artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-latest-artifact
        path: ./windows-latest-artifact
    - name: Verify Artifacts
      run: "\n        for platform in ubuntu-latest macos-latest windows-latest; do\n            echo \"Listing contents of $platform artifact:\"\n            ls -R $platform-artifact\n            echo \"\"\n        done\n        "
name: CI
on:
- push
- pull_request
