jobs:
  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build C++
      run: mkdir -p build && cd build && cmake .. && make
    - name: Create artifact
      run: echo "This is a sample artifact for ${{ runner.os }}" > artifact.txt
    - name: Debug - List directory contents
      run: ls -la
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-latest-artifact
        path: artifact.txt
        retention-days: 1
    - env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: text/plain
        asset_name: macos-latest-artifact.txt
        asset_path: ./artifact.txt
        upload_url: https://uploads.github.com/repos/RPDevJesco/OOHD/releases/164908773/assets{?name,label}
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build C++
      run: mkdir -p build && cd build && cmake .. && make
    - name: Create artifact
      run: echo "This is a sample artifact for ${{ runner.os }}" > artifact.txt
    - name: Debug - List directory contents
      run: ls -la
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-latest-artifact
        path: artifact.txt
        retention-days: 1
    - env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: text/plain
        asset_name: ubuntu-latest-artifact.txt
        asset_path: ./artifact.txt
        upload_url: https://uploads.github.com/repos/RPDevJesco/OOHD/releases/164908773/assets{?name,label}
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build C++
      run: mkdir build && cd build && cmake .. && cmake --build .
    - name: Create artifact
      run: echo "This is a sample artifact for ${{ runner.os }}" > artifact.txt
    - name: Debug - List directory contents
      run: ls -la
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-latest-artifact
        path: artifact.txt
        retention-days: 1
    - env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: text/plain
        asset_name: windows-latest-artifact.txt
        asset_path: ./artifact.txt
        upload_url: https://uploads.github.com/repos/RPDevJesco/OOHD/releases/164908773/assets{?name,label}
  verify_artifacts:
    needs:
    - build_ubuntu
    - build_macos
    - build_windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download ubuntu-latest artifact
      uses: actions/download-artifact@v4
      with:
        name: ubuntu-latest-artifact
        path: ./ubuntu-latest-artifact
    - name: Download macos-latest artifact
      uses: actions/download-artifact@v4
      with:
        name: macos-latest-artifact
        path: ./macos-latest-artifact
    - name: Download windows-latest artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-latest-artifact
        path: ./windows-latest-artifact
    - name: Verify artifacts
      run: "\n        for platform in ubuntu-latest macos-latest windows-latest; do\n            echo \"Content of $platform artifact:\"\n            cat $platform-artifact/artifact.txt\n            echo \"\"\n        done\n        "
name: CI
on:
- push
- pull_request
